# Generated by Django 4.0.6 on 2022-09-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimpleLogger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("count_of_visits", models.PositiveIntegerField(default=0)),
                ("last_visit", models.DateTimeField()),
            ],
        ),
    ]
