# Generated by Django 4.0.6 on 2022-07-27 22:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(
                    choices=[('Phone', 'phones'), ('email', 'Email'), ('Telegram', 'telegram'),
                             ('LinkedIn', 'Linkedin')], default='Phone', max_length=255, verbose_name='Contact_type')),
                ('contact_value', models.CharField(max_length=255, verbose_name='Contact_value')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='tag_name', max_length=255, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Contact_name', max_length=255, verbose_name='Name')),
                ('birthday', models.DateField(default=datetime.datetime(1998, 7, 20, 0, 0), help_text='date_of_birth',
                                              verbose_name='Birth')),
                ('contact_value', models.ManyToManyField(related_name='contact_detail', to='phone_book.contactdetail')),
                ('tags', models.ManyToManyField(related_name='tags', to='phone_book.tag')),
            ],
        ),
    ]
