# Generated by Django 4.0.6 on 2022-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(help_text='Contact_name', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='contact_type',
            field=models.CharField(choices=[('Phone', 'phones'), ('email', 'Email'), ('Telegram', 'telegram'), ('LinkedIn', 'Linkedin')], default='Phone', max_length=255, unique=True, verbose_name='Contact_type'),
        ),
    ]
