# Generated by Django 4.0.6 on 2022-07-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('phone_book', '0002_alter_contact_phone_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
