name: Main workflow

# на что оно будет срабатывать(команды из Git)
on: [push, pull_request]

# что нужно сделать
jobs:
  main:

#   в каком исполнителе(операционке) это будет запускаться(можно создать свой обработчик)
#   для этого нужен публичный репо
    runs-on: ubuntu-20.04
#   далее опишем шаги, которые будут выполняться
    steps:
#     Переключиться на репозиторий
      - name: Checkout
#     шаг для получения данных с нашего репозитория:
#     это по сути отсылка на аккаунт с именем actions, репозиторий checkout, tags - v3
#     сюда можно создать доп. workflows, которые подключать к этому workflow
        uses: actions/checkout@v3
#     установка python
      - name: Set up Python
        uses: actions/setup-python@v4
#     это по сути аргументы,которые мы передаём в workflow
        with:
          python-version: "3.10"

#     Установка зависимостей (действие с самописной командой)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt

#     Сделать всё, что было в pre-commit (Минус этого варианта, что у вас не показывается точечно какаой этап)
      - name: Run pre-commit hook
        run: pre-commit run

# Обычно в workflow запускают тесты и если команды выполняются хорошо, то мы собираем наше приложение и даём команду в другое место,
#что бы развернуть наше приложение
# Это называется continious integration/continious delivery (CI/CD)





